### ISSUE TITLE
Implement ISO19115-1

### ISSUE THREAD

**Issue by etj** [geosolutions-it/pycsw#1]
# Description

# Environment

- operating system:
- Python version:
- pycsw version:
- source/distribution
  - [ ] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [ ] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 

# Steps to Reproduce

# Additional Information

**Comment by simboss** [comment]
We are not going to use pyCSW but rather GeoNetwork.
